---
cabinet:
    environment: http://api_host:api_port
    # Examples
    dev_local: http://localhost:5050
    testing: http://localhost:5050

# Values for api_host and api_port will come from the cabinet_api config/config.yaml file 